version: "3"

services:
    timescaledb:
        image: timescale/timescaledb-ha:pg16
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: verkeers-data
